baseURL = "https://resources.gburin.com/"
languageCode = "en-us"
title = "Materiais de aulas"
theme = "hyde"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
author = "Gustavo Burin"

[params]
  Subtitle = "Tutoriais e exercícios"
  GithubID = "gburin"
  TwitterID = "gustavoburin"
  AnalyticsID = "UA-117053218-3"
  DisqusShortname = "gburin"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  math = true
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."
  googleAnalytics = "UA-111310024-1"
  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "15:04"
# Setting permalink rules
  themeColor = "theme-base-0c"
  layoutReverse = true
  description = "Tutoriais e Exercícios"
  homepage = "https://www.gburin.com"
  repo = "https://www.github.com/gburin"
  author = "gustavoburin"
[permalinks]
    post = "/:slug/"
